#!/bin/bash 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1979.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1980.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1981.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1982.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1983.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1984.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1985.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1986.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1987.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1988.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1989.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1990.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1991.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1992.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1993.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1994.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1995.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1996.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1997.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1998.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1979.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1980.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1981.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1982.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1983.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1984.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1985.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1986.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1987.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1988.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1989.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1990.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1991.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1992.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1993.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1994.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1995.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1996.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1997.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1998.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1979.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1980.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1981.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1982.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1983.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1984.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1985.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1986.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1987.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1988.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1989.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1990.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1991.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1992.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1993.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1994.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1995.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1996.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1997.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1998.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2018.nc
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1979.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1980.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1981.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1982.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1983.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1984.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1985.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1986.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1987.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1988.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1989.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1990.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1991.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1992.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1993.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1994.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1995.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1996.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1997.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1998.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2018.nc 
